@echo off
title Backup your hardrive [RELEASE V1.0]
color 02
:start
	CHOICE /C ABCDEFGHIJKLMNOPQRSTUVWXYZ /N /M "Choose the drive you want to BACKUP: [A, B, C, D:, E, F, G, H, I ...?]"
		IF ERRORLEVEL 1 SET DRIVE=A:
		IF ERRORLEVEL 2 SET DRIVE=B:
		IF ERRORLEVEL 3 SET DRIVE=C:
		IF ERRORLEVEL 4 SET DRIVE=D:
		IF ERRORLEVEL 5 SET DRIVE=E:
		IF ERRORLEVEL 6 SET DRIVE=F:
		IF ERRORLEVEL 7 SET DRIVE=G:
		IF ERRORLEVEL 8 SET DRIVE=H:
		IF ERRORLEVEL 9 SET DRIVE=I:
		IF ERRORLEVEL 10 SET DRIVE=J:
		IF ERRORLEVEL 11 SET DRIVE=K:
		IF ERRORLEVEL 12 SET DRIVE=L:
		IF ERRORLEVEL 13 SET DRIVE=M:
		IF ERRORLEVEL 14 SET DRIVE=N:
		IF ERRORLEVEL 15 SET DRIVE=O:
		IF ERRORLEVEL 16 SET DRIVE=P:
		IF ERRORLEVEL 17 SET DRIVE=Q:
		IF ERRORLEVEL 18 SET DRIVE=R:
		IF ERRORLEVEL 19 SET DRIVE=S:
		IF ERRORLEVEL 20 SET DRIVE=T:
		IF ERRORLEVEL 21 SET DRIVE=U:
		IF ERRORLEVEL 22 SET DRIVE=V:
		IF ERRORLEVEL 23 SET DRIVE=W:
		IF ERRORLEVEL 24 SET DRIVE=X:
		IF ERRORLEVEL 25 SET DRIVE=Y:
		IF ERRORLEVEL 26 SET DRIVE=Z:
CLS
	CHOICE /C ABCDEFGHIJKLMNOPQRSTUVWXYZ /N /M "To wich drive do you want the backup to save: [A, B, C, D:, E, F, G, H, I ...?]"
		IF ERRORLEVEL 1 SET DRIVEB=A:
		IF ERRORLEVEL 2 SET DRIVEB=B:
		IF ERRORLEVEL 3 SET DRIVEB=C:
		IF ERRORLEVEL 4 SET DRIVEB=D:
		IF ERRORLEVEL 5 SET DRIVEB=E:
		IF ERRORLEVEL 6 SET DRIVEB=F:
		IF ERRORLEVEL 7 SET DRIVEB=G:
		IF ERRORLEVEL 8 SET DRIVEB=H:
		IF ERRORLEVEL 9 SET DRIVEB=I:
		IF ERRORLEVEL 10 SET DRIVEB=J:
		IF ERRORLEVEL 11 SET DRIVEB=K:
		IF ERRORLEVEL 12 SET DRIVEB=L:
		IF ERRORLEVEL 13 SET DRIVEB=M:
		IF ERRORLEVEL 14 SET DRIVEB=N:
		IF ERRORLEVEL 15 SET DRIVEB=O:
		IF ERRORLEVEL 16 SET DRIVEB=P:
		IF ERRORLEVEL 17 SET DRIVEB=Q:
		IF ERRORLEVEL 18 SET DRIVEB=R:
		IF ERRORLEVEL 19 SET DRIVEB=S:
		IF ERRORLEVEL 20 SET DRIVEB=T:
		IF ERRORLEVEL 21 SET DRIVEB=U:
		IF ERRORLEVEL 22 SET DRIVEB=V:
		IF ERRORLEVEL 23 SET DRIVEB=W:
		IF ERRORLEVEL 24 SET DRIVEB=X:
		IF ERRORLEVEL 25 SET DRIVEB=Y:
		IF ERRORLEVEL 26 SET DRIVEB=Z:

%DRIVEB%
cd /
mkdir Backup
CLS
CHOICE /C yn /N /M "Back up only user files [y:n] ?"
		IF ERRORLEVEL 1 SET userfiles=y
		IF ERRORLEVEL 2 SET userfiles=n

if %userfiles%==y goto userfilesonly
if %userfiles%==n goto allfilesbackup

:allfilesbackup
CLS
xcopy /R /E /H /Y /D /C /F "%DRIVE%/" "%DRIVEB%/backup"
attrib -h -s "%DRIVEB%/backup"
pause
CLS
echo Backup of all your files is now complete
Echo Completed on %DATE% %TIME%
pause
exit

:userfilesonly
CLS
set /p USERNAME= What is the USERNAME you want to backup?
xcopy /R /E /H /Y /C /D /F "%DRIVE%/users/%USERNAME%" "%DRIVEB%/backup/%USERNAME%"
attrib -h -s "%DRIVEB%/backup/%USERNAME%"
pause
CLS
echo Backup of all your user files are now complete
Echo Completed on %DATE% %TIME%
pause
exit
